### ISSUE TITLE
[GNOME 47] Dialog overlays buttons are not themed correctly

### ISSUE THREAD

**Issue by gnolooo** [daniruiz/flat-remix-gnome#234] opened 2024-10-23 09:48 UTC
As per title, in Gnome 47 dialog overlays buttons (I believe they are called so) are not themed correctly.
I'm using Gnome 47 with the latest Flat Remix version (fac3b8e).
This is what I mean:

![Screenshot From 2024-10-23 11-21-42](https://github.com/user-attachments/assets/8dfafc32-4f5a-46b6-a42d-f152850411ea)

The buttons "Annulla" (Undo) and "Termina sessione" (End session) are as plain black as the background, making them kinda hard to distinguish. Clicking on them still works, executing the action, but there's no theming whatsoever.
I believe in Gnome 46 there were: grey outlines around those buttons; an animation when hovering with the cursor (slightly changing color to a dark grey, like any other element - eg. quick tiles, notifications or any other button); another animation when clicking on them (changing color again, I believe to theme accent color - in my case blue - but I don't really remember).
I'm sorry this is hard to explain and to understand, but I have no way to reproduce the previous state other than rolling back both the theme and the whole Gnome shell (which is kind of an overkill).

**Comment by gnolooo** [comment] 2024-10-24 09:35
I've found other overlays too:

![Screenshot From 2024-10-24 11-32-54](https://github.com/user-attachments/assets/731e4e3e-41cc-4b4e-ab7a-111326c84fe1)

![Screenshot From 2024-10-24 11-33-01](https://github.com/user-attachments/assets/e7c71a57-5cf5-4a6c-8cd3-653848d4e862)

Btw I don't exactly know why languages are mismatched... but that's unrelated.

**Comment by daniruiz** [comment] 2024-12-08 10:45
I can't reproduce this issue with the latest updates so this should be fixed now

**Closed by daniruiz** 2024-12-08 10:45 UTC
