### ISSUE TITLE
Login screen is broken with flat-remix-gnome 3.30.14

### ISSUE THREAD

**Issue by jeffryang24** [daniruiz/flat-remix-gnome#68] opened 2019-03-01 06:51 UTC
Hi, last day I updated flat-remix package to the latest version. Here is my specification:

- Ubuntu 18.04 LTS x86_64
- flat-remix/bionic,now 1.64 amd64 [installed]
- flat-remix-gnome/bionic,now 3.30.14-1 amd64 [installed]
- flat-remix-gtk/bionic,now 2.8-2 amd64 [installed]
- GNOME Shell 3.28.3

**Expected behaviour**

The login screen is not broken.

**Actual Behaviour**

![flat-remix-login-screen-issue-1](https://user-images.githubusercontent.com/8284757/53621249-85a43380-3c28-11e9-9160-6a4184fbf30e.jpg)

The login screen is broken (the background also doesn't show up).

**Step to reproduce**

1. Update flat-remix package from ppa (https://launchpad.net/~daniruiz/+archive/ubuntu/flat-remix).
2. Reboot and wait until the login screen shows up.

**Comment by jeffryang24** [comment] 2019-03-01 06:53
Hmm.. Or your latest package is only for GNOME Shell ^3.30? :thinking:

**Comment by georgemickael-b** [comment] 2019-03-01 08:23
Same issue. It seems there are two login screens . one over other.

**Comment by daniruiz** [comment] 2019-03-01 10:46
Upppss... that happens when GDM doesn't find the background file. I might have messed it a bit with symlinks :face_with_head_bandage: 
It'll be an update for tomorrow, stay tunned.

**Comment by daniruiz** [comment] 2019-03-01 16:51
Well... I can't see why it fails. In my PC is working fine. Can you try to completely uninstall and reinstall it:
```bash
sudo apt remove flat-remix-gnome
sudo apt install flat-remix-gnome
```

**Comment by georgemickael-b** [comment] 2019-03-01 16:57
@daniruiz I tried several times install and reinstalling
 The issue persists.
If this will help you, even after uninstalling the theme completely, the problem still remains. 
Something permanently is changed if I am correct.

I am using ubuntu 18.04.2  which has gnome 3.28.3

**Comment by daniruiz** [comment] 2019-03-01 17:08
Can you try to execute this?
```sh
sudo update-alternatives --config gdm3.css
```
And select Yaru theme

**Comment by georgemickael-b** [comment] 2019-03-01 17:19
I won't be able run it as I rebooted the system and installed your theme by copy pasting files to ./themes and ignoring login page configuration..
It might not be best for me to test at this point.. but this issue's creater, if still waiting on this resolution n, might be able to run.

But I didn't run the command when I had the issue,if my memory serves me right, I didnt find Yaru theme.  There were several flat remix CSS and one ubuntu.css .

**Comment by daniruiz** [comment] 2019-03-01 17:37
Anyway to reinstall default desktop just run
```
sudo apt install --reinstall ubuntu-gnome-desktop gdm3
```

**Comment by jeffryang24** [comment] 2019-03-02 06:03
I already tried to reinstall `flat-remix-gnome` as above method, but still no change.

I suspect that there are some miss-configuration inside my `/usr/share/themes/Flat-Remix` (all Flat-Remixs directory).

![wrong_ln_target](https://user-images.githubusercontent.com/8284757/53677990-412d9c00-3ceb-11e9-91ad-929358b47d84.png)

Also the `/usr/share/gnome-shell/gnome-shell-theme.gresource` is still using the ubuntu default one (doesn't link to the Flex Remix version).

![gnome-shell-resource](https://user-images.githubusercontent.com/8284757/53678004-8356dd80-3ceb-11e9-9884-0db2888da3fb.png)

**Comment by daniruiz** [comment] 2019-03-02 09:36
The problem isn't the gresource file but about /usr/share/gnome-shell/theme/gdm3.css

**Comment by Und3rCover96** [comment] 2019-03-02 19:45
i have this issue and not fix yet please fix it

**Comment by daniruiz** [comment] 2019-03-03 15:02
It is fixed now. Please update it to 3.30.14-2 and tell me if there is any other issue.
I'm really sorry about this guys, just understand it's very difficult to maintain that much different distros and packages.

**Comment by Und3rCover96** [comment] 2019-03-03 15:16
yes it fixes tnx  dear daniruiz

**Closed** 2019-03-03 15:19 UTC
