### ISSUE TITLE
Oddly placed buttons in Gnome Shell 44

### ISSUE THREAD

**Issue by dawetmaster** [daniruiz/flat-remix-gnome#218] opened 2023-04-26 00:42 UTC
![image](https://user-images.githubusercontent.com/71202342/234437351-1c5d5c37-718a-4cd9-b159-b8582b8c4cc3.png)

Sorry, the dropdown buttons in Gnome Shell 44 is weirdly placed not as intended (should be in the buttons). I would like to look back for your response and thank you for this beautiful theme.

**Comment by daniruiz** [comment] 2023-04-26 06:24
Are you using the theme in branch gnome-44? 
https://github.com/daniruiz/flat-remix-gnome/tree/gnome-44

**Comment by olhapi** [comment] 2023-04-27 12:08
have a similar issue in Fedora 38 (gnome-44)
![image](https://user-images.githubusercontent.com/4780263/234857058-8ea7303b-24ab-408b-a43c-bfd62116e79e.png)

installed theme from dnf
![image](https://user-images.githubusercontent.com/4780263/234857496-1f103186-9c0d-459c-ae41-51e3a09fe536.png)

**Comment by jumesa** [comment] 2023-05-03 10:33
@dawetmaster @olhapi @daniruiz 
I have tested gnome 44 version and works fine:
I guess they are using a bad version, remove installed version and install gnomne 44 version.
The instructions are in [drasite.](https://drasite.com/flat-remix-gnome), search for `Gnome 44`
```
git clone --branch gnome-44 https://github.com/daniruiz/flat-remix-gnome
cd flat-remix-gnome
make && sudo make install
```

**Comment by daniruiz** [comment] 2023-05-03 12:04
I'm closing this as it's not a bug. Make sure you are using the correct version of the theme for your shell version ;)

I'll merge the branch gnome-44 once gnome 44 arrives to arch stable repositories

**Closed by daniruiz** 2023-05-03 12:04 UTC

**Comment by olhapi** [comment] 2023-05-03 12:40
the issue seems fixed after compiling directly from gnome-44 branch
